# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'Full Stack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FullStackCodingBot
   pod 'RxSwift'
   pod 'RxCocoa'
   pod 'NSObject+Rx'
   pod 'SwiftLint'
   pod 'Google-Mobile-Ads-SDK'
   pod 'Firebase/Core'
   pod 'Firebase/Database'
   pod 'Firebase/Auth'
   pod 'Action'

   target 'Full StackTests' do

     # Pods for FullStackTest
     pod 'RxSwift'
     pod 'RxCocoa'
     pod 'NSObject+Rx'
     pod 'Action'
     pod 'SwiftLint'
  end
end
