# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FullStackCodingBot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FullStackCodingBot
   pod 'RxSwift'
   pod 'RxCocoa'
   pod 'NSObject+Rx'
   pod 'Alamofire'
   pod 'Action'
   pod 'SwiftLint'
   pod 'RxDataSources'
end
