# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Full Stack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FullStackCodingBot
   pod 'RxSwift'
   pod 'RxCocoa'
   pod 'NSObject+Rx'
   pod 'Alamofire'
   pod 'Action'
   pod 'SwiftLint'
   pod 'GhostTypewriter'
   pod 'Google-Mobile-Ads-SDK'
   pod 'Firebase/Core'
   pod 'Firebase/Database'
   pod 'Firebase/Auth'

   target 'Full StackTests' do

     # Pods for FullStackTest
     pod 'RxSwift'
     pod 'RxCocoa'
     pod 'NSObject+Rx'
     pod 'Alamofire'
     pod 'Action'
     pod 'SwiftLint'
     pod 'GhostTypewriter'
  end
end
